@startuml
left to right direction
actor "Auteur" as Author
actor "Administrateur" as Admin

Author <|-- Admin

package "Back-Office (Admin)" {
  ' --- 1. Espace Commun ---
  usecase "Voir le Dashboard (Stats)" as UC_Dashboard

  ' --- 2. Gestion Content ---
  usecase "Gérer les Articles" as UC_CRUD
  usecase "Soumettre pour validation" as UC_Submit
  usecase "Valider & Publier" as UC_Publish

  ' --- 3. Gestion Admin ---
  usecase "Gérer les Catégories" as UC_Cats
  usecase "Gérer les Tags" as UC_Tags
  usecase "Gérer les Utilisateurs" as UC_Users
  usecase "Attribuer un Rôle (Auteur/Admin)" as UC_Roles
  usecase "Modérer les Commentaires" as UC_Moderate
}

' Relations Auteur
Author -- UC_Dashboard
Author -- UC_CRUD

' Extensions Gérer Articles
UC_Submit .> UC_CRUD : <<extend>>
UC_Publish .> UC_CRUD : <<extend>>

' Relations Admin
Admin -- UC_Cats
Admin -- UC_Tags
Admin -- UC_Users
Admin -- UC_Moderate

UC_Roles .> UC_Users : <<extend>>

@enduml
