@startuml
left to right direction
actor "Système Externe" as System

package "Sprint 5 : API REST" {
  usecase "Lister les articles (API)" as UC_List
  usecase "Détail article (API)" as UC_Detail
  usecase "Connexion API (Token)" as UC_Auth
}

System -- UC_List
System -- UC_Detail
System -- UC_Auth
@enduml
