@startuml
left to right direction
actor "Auteur" as Author
actor "Administrateur" as Admin
package "Sprint 3 : Auth & Permissions" {
  usecase "Se connecter / S'inscrire" as UC_Auth
  
  usecase "Gérer les Articles" as UC_Manage
  
  ' Workflow Article (Extensions)
  usecase "Créer Article (Brouillon)" as UC_Create
  usecase "Soumettre à validation" as UC_Submit
  usecase "Valider & Publier" as UC_Publish
  usecase "Rejeter un Article" as UC_Reject
}

' Relations
UC_Create .> UC_Manage : <<extend>>
UC_Submit .> UC_Manage : <<extend>>
UC_Publish .> UC_Manage : <<extend>>
UC_Reject .> UC_Manage : <<extend>>

' Acteurs
Author -- UC_Auth
Author -- UC_Manage

Admin -- UC_Auth
Admin -- UC_Manage
@enduml
