@startuml
left to right direction
actor "Visiteur" as Guest
actor "Membre" as Member

Guest <|-- Member

package "Front-Office (Web Public)" {
  usecase "Consulter la liste des articles" as UC_List
  usecase "Lire un article (Détail)" as UC_Read
  
  usecase "Rechercher des articles (AJAX)" as UC_Search
  usecase "Filtrer (Catégorie / Tag)" as UC_Filter
  
  usecase "Se connecter (Email / Google / GitHub)" as UC_Login
  usecase "S'inscrire" as UC_Register
  usecase "Réinitialiser mot de passe" as UC_ResetPwd
  
  usecase "Lire les commentaires" as UC_ReadComments
  usecase "Poster un commentaire" as UC_PostComment
  
  usecase "Ajouter aux favoris" as UC_AddFavorite
  usecase "Voir son Profil" as UC_Profile
  usecase "Partager sur les réseaux" as UC_Share
}

' Relations Visiteur
Guest -- UC_List
Guest -- UC_Read
Guest -- UC_Login
Guest -- UC_Register
Guest -- UC_ResetPwd

' Relations Membre
Member -- UC_PostComment
Member -- UC_AddFavorite
Member -- UC_Profile

' -- Relations <<extend>> --
UC_Search .> UC_List : <<extend>>
UC_Filter .> UC_List : <<extend>>
UC_ReadComments .> UC_Read : <<extend>>
UC_PostComment .> UC_Read : <<extend>>
UC_AddFavorite .> UC_Read : <<extend>>
UC_Share .> UC_Read : <<extend>>

' -- Relations <<include>> --
UC_PostComment ..> UC_Login : <<include>>
UC_AddFavorite ..> UC_Login : <<include>>

@enduml
