@startuml
left to right direction
actor "Visiteur" as Guest

package "Espace Lecture & Découverte" {
  usecase "Consulter la liste des articles" as UC_List
  usecase "Lire un article (Détail)" as UC_Read
  usecase "Rechercher des articles (AJAX)" as UC_Search
  usecase "Filtrer (Catégorie / Tag)" as UC_Filter
}

' Relations
Guest -- UC_List
Guest -- UC_Read

' Extensions
UC_Search .> UC_List : <<extend>>
UC_Filter .> UC_List : <<extend>>

@enduml
