@startuml
left to right direction
actor "Visiteur" as Guest
actor "Auteur" as Author

Guest <|-- Author

package "Front-Office (Web Public)" {
  usecase "Consulter la liste des articles" as UC_List
  usecase "Lire un article (Détail)" as UC_Read
  
  usecase "Rechercher des articles" as UC_Search
  usecase "Filtrer (Catégorie / Tag)" as UC_Filter
  
  usecase "Se connecter" as UC_Login
  usecase "S'inscrire" as UC_Register
  
  usecase "Lire les commentaires" as UC_ReadComments
  usecase "Poster un commentaire" as UC_PostComment
}

' Relations Visiteur pour les cas de base
Guest -- UC_List
Guest -- UC_Read
Guest -- UC_Login
Guest -- UC_Register

' Relations Auteur (Spécifique)
Author -- UC_PostComment

' -- Relations <<extend>> (Options) --
UC_Search .> UC_List : <<extend>>
UC_Filter .> UC_List : <<extend>>
UC_Filter .> UC_Search : <<extend>>
UC_ReadComments .> UC_Read : <<extend>>
UC_PostComment .> UC_Read : <<extend>>

' -- Relations <<include>> (Obligations) --
UC_PostComment ..> UC_Login : <<include>>

@enduml