@startuml
left to right direction
actor "Root" as User

package "Sprint 2 : Back-Office sans Sécurité" {
  usecase "Gérer les Articles" as UC_CRUD
  usecase "Uploader une image" as UC_Media
  usecase "Soumettre pour validation" as UC_Submit
  usecase "Valider & Publier" as UC_Publish
  usecase "Rechercher & Filtrer" as UC_Search
}

User -- UC_CRUD

' Relations
UC_CRUD ..> UC_Media : <<include>>
UC_Submit .> UC_CRUD : <<extend>>
UC_Publish .> UC_CRUD : <<extend>>
UC_Search .> UC_CRUD : <<extend>>
@enduml
